globalThis.ENBATiktokPieces = [
  {
    id: "TT01",
    group: 1,
    title: "No hace falta irte lejos para vivir esto",
    pillar: "Buenos Aires desde el agua",
    objective: "Descubrimiento",
    format: "Video principal / atardecer",
    mediaType: "video",
    media: "media/956CF4EA-ED6E-49B9-B883-B17C6A2D7403.mp4",
    poster: "posters/956CF4EA.jpg",
    alt: "Atardecer en el río con ciudad al fondo",
    hook: "No hace falta irte lejos para vivir esto",
    screenText: ["No hace falta irte lejos", "para vivir esto", "Buenos Aires desde el agua"],
    captionLead: "Abrimos el canal con río, atardecer y ciudad al fondo: el ángulo más fuerte para abrir la cuenta.",
    cta: "Guardalo para acordarte de que esto también es Buenos Aires.",
    hashtags: ["#ENBA", "#BuenosAires", "#RioDeLaPlata"],
    assetNote: "Nuevo material 27/04 · clip 956CF4EA atardecer + ciudad",
    editNote: "Mantener el plano respirado y cargar el texto en 3 golpes grandes. Si lleva marca, usar icono ENBA real muy chico solo al cierre."
  },
  {
    id: "TT02",
    group: 1,
    title: "Tu primera vez en un velero puede empezar acá",
    pillar: "Primera vez",
    objective: "Fricción baja",
    format: "Video vela / aprendizaje",
    mediaType: "video",
    media: "media/IMG_5615.MOV",
    poster: "posters/IMG_5615.jpg",
    alt: "Cubierta y vela en movimiento con clima de aprendizaje",
    hook: "Tu primera vez en un velero puede empezar acá",
    screenText: ["Tu primera vez", "en un velero", "puede empezar acá"],
    captionLead: "La pieza sigue bajando ansiedad desde una promesa simple y directa, aunque use un clip más ligado a aprendizaje.",
    cta: "Escribinos si querés tener tu primera salida.",
    hashtags: ["#ENBA", "#espacionautico", "#PrimeraVez", "#Velero"],
    assetNote: "Nuevo material 27/04 · IMG_5615.MOV",
    editNote: "Usar la vela y la cubierta como soporte del mensaje formativo, sin hacerlo solemne."
  },
  {
    id: "TT03",
    group: 1,
    title: "Buenos Aires se ve distinta desde el río",
    pillar: "Buenos Aires desde el agua",
    objective: "Descubrimiento",
    format: "Video río abierto / ciudad lejana",
    mediaType: "video",
    media: "media/5c04e430-97c1-42ee-980c-5cfac81e6d66.mp4",
    poster: "posters/5c04e430.jpg",
    alt: "Río abierto con vela y ciudad lejana",
    hook: "Buenos Aires se ve distinta desde el río",
    screenText: ["Buenos Aires", "volvemos a encontrarnos", "pero en el río"],
    captionLead: "Acá ya no va por la ciudad vista distinto sino por el reencuentro con Buenos Aires desde otra lógica.",
    cta: "Seguinos para ver Buenos Aires desde otro lugar.",
    hashtags: ["#ENBA", "#BuenosAires", "#Velero"],
    assetNote: "Nuevo material 27/04 · 5c04e430 río abierto + ciudad",
    editNote: "Arrancar con agua y vela ya en cuadro; la ciudad tiene que sentirse fondo, no postal."
  },
  {
    id: "TT04",
    group: 1,
    title: "Qué pasa en una salida real en velero",
    pillar: "Backstage real",
    objective: "Mostrar experiencia",
    format: "Video embarque / marina",
    mediaType: "video",
    media: "media/IMG_5454.MOV",
    poster: "posters/IMG_5454.jpg",
    alt: "Salida real desde marina",
    hook: "Qué pasa en una salida real en velero",
    screenText: ["Marina", "embarcar", "salir en serio", "río de verdad"],
    captionLead: "Sirve para mostrar secuencia concreta y humana sin depender de reels viejos.",
    cta: "Mandáselo a quien se subiría con vos.",
    hashtags: ["#ENBA", "#SalidaEnVelero", "#RioDeLaPlata"],
    assetNote: "Nuevo material 27/04 · IMG_5454.MOV",
    editNote: "Editar como resumen corto: embarque, paso a bordo y salida."
  },
  {
    id: "TT05",
    group: 1,
    title: "No necesitás experiencia para subirte",
    pillar: "Primera vez",
    objective: "Bajar ansiedad",
    format: "Video POV / agua",
    mediaType: "video",
    media: "media/IMG_5601.MOV",
    poster: "posters/IMG_5601.jpg",
    alt: "POV del río desde cubierta",
    hook: "No necesitás experiencia para subirte",
    screenText: ["No necesitás experiencia", "ni venir sabiendo", "solo querer probar"],
    captionLead: "El río puede parecer lejano; esta pieza lo vuelve simple y accesible.",
    cta: "Mandáselo a quien siempre dice “me da cosa”.",
    hashtags: ["#ENBA", "#PrimeraVez", "#SalidaEnVelero"],
    assetNote: "Nuevo material 27/04 · IMG_5601.MOV",
    editNote: "Hook textual muy temprano y ritmo amable, casi de invitación."
  },
  {
    id: "TT06",
    group: 2,
    title: "Aprender a navegar no arranca en un aula, arranca acá",
    pillar: "Aprender a navegar",
    objective: "Escuela",
    format: "Video maniobra / cabos",
    mediaType: "video",
    media: "media/IMG_5492.MOV",
    poster: "posters/IMG_5492.jpg",
    alt: "Maniobra práctica en cubierta",
    hook: "Aprender a navegar no arranca en un aula, arranca acá",
    screenText: ["No arranca en un aula", "arranca en cubierta", "y con práctica real"],
    captionLead: "La pieza más clara para escuela con material nuevo: manos, cabos, acción real.",
    cta: "Consultanos si querés aprender a navegar de verdad.",
    hashtags: ["#ENBA", "#espacionautico", "#EscuelaDeNautica", "#AprenderANavegar"],
    assetNote: "Nuevo material 27/04 · IMG_5492.MOV",
    editNote: "Usar primeros planos de acción y una voz en off corta."
  },
  {
    id: "TT07",
    group: 2,
    title: "Lo que nadie te cuenta de aprender a navegar",
    pillar: "Aprender a navegar",
    objective: "Curiosidad",
    format: "Video cubierta / condiciones",
    mediaType: "video",
    media: "media/IMG_5614.MOV",
    poster: "posters/IMG_5614.jpg",
    alt: "Cubierta y cielo abierto durante navegación",
    hook: "Lo que nadie te cuenta de aprender a navegar",
    screenText: ["No es memorizar", "es leer el barco", "y sentir el río"],
    captionLead: "TikTok agradece este tono medio confidencial cuando el visual sostiene autenticidad.",
    cta: "Seguinos si querés ver cómo se aprende en el río.",
    hashtags: ["#ENBA", "#espacionautico", "#EscuelaDeNautica", "#Navegacion"],
    assetNote: "Nuevo material 27/04 · IMG_5614.MOV",
    editNote: "Dejar que el cielo y la cubierta hagan atmósfera; no sobrecargar de texto."
  },
  {
    id: "TT08",
    group: 2,
    title: "Así se siente tener el timón por primera vez",
    pillar: "Aprender a navegar",
    objective: "Sensación",
    format: "Video cubierta / sol / primera vez",
    mediaType: "video",
    media: "media/IMG_4576.MOV",
    trimStart: 3.5,
    poster: "posters/IMG_4576.jpg",
    alt: "Cubierta al sol con sensación de primera experiencia",
    hook: "Así se siente tener el timón por primera vez",
    screenText: ["Primer timón", "primera respuesta", "primer click"],
    captionLead: "Este clip funciona mejor para sensación que para explicación: aire, sol y barco respondiendo.",
    cta: "Guardalo si querés vivir ese primer click.",
    hashtags: ["#ENBA", "#PrimeraVez", "#Navegacion"],
    assetNote: "Asset-bank · grupos-experiencia/IMG_4576.MOV",
    editNote: "Tratarla como recuerdo físico y no como pieza descriptiva; este reemplazo da más navegación real y más aire."
  },
  {
    id: "TT09",
    group: 2,
    title: "No hace falta venir sabiendo. Hace falta venir",
    pillar: "Escuela",
    objective: "Conversión suave",
    format: "Video onboard / persona",
    mediaType: "video",
    media: "media/IMG_5623.MOV",
    poster: "posters/IMG_5623.jpg",
    alt: "Persona en cubierta durante navegación real",
    hook: "No hace falta venir sabiendo. Hace falta venir",
    screenText: ["No hace falta venir sabiendo", "hace falta venir", "y practicar"],
    captionLead: "Con gente real a bordo esta frase gana más verdad y menos tono abstracto.",
    cta: "Instructores de primera. ¿Querés hacerlo? Vení a aprender en serio.",
    hashtags: ["#ENBA", "#espacionautico", "#EscuelaDeNautica", "#AprenderANavegar"],
    assetNote: "Nuevo material 27/04 · IMG_5623.MOV",
    editNote: "Texto protagonista, con presencia humana real para que no quede solo en manifiesto."
  },
  {
    id: "TT10",
    group: 2,
    title: "3 cosas que ves en el río cuando subís a un velero",
    pillar: "Aprender a navegar",
    objective: "Formato lista",
    format: "Video río abierto / lista",
    mediaType: "video",
    media: "media/IMG_5600.MOV",
    poster: "posters/IMG_5600.jpg",
    alt: "Río abierto y velero a distancia",
    hook: "3 cosas que ves en el río cuando subís a un velero",
    screenText: ["1. Horizonte real", "2. Tráfico y viento", "3. La ciudad desde otro lugar"],
    captionLead: "Formato lista simple y visual, ideal para testear shares y retención corta.",
    cta: "Comentá qué te daría más ganas de subirte.",
    hashtags: ["#ENBA", "#RioDeLaPlata", "#Velero"],
    assetNote: "Nuevo material 27/04 · IMG_5600.MOV",
    editNote: "Mantener 3 beats muy claros y no pasarse de 12-15 segundos."
  },
  {
    id: "TT11",
    group: 3,
    title: "Si tu plan de finde siempre es igual, mirá esto",
    pillar: "Deseo / estilo de vida",
    objective: "Interrupción",
    format: "Video grupo a bordo / clima de grupo",
    mediaType: "video",
    media: "media/IMG_4635.MOV",
    trimStart: 4.0,
    poster: "posters/IMG_4635.jpg",
    alt: "Grupo real a bordo con clima de amigos y salida compartida",
    hook: "Si tu plan de finde siempre es igual, mirá esto",
    screenText: ["Si tu finde siempre se ve igual", "tal vez el problema", "es el plan"],
    captionLead: "Esta sí entra mejor en el ángulo 'plan con amigos': grupo real arriba del barco y contexto claro sin verse actuado.",
    cta: "Mandáselo a tu grupo y armate la próxima juntada.",
    hashtags: ["#ENBA", "#PlanConAmigos", "#SalidaEnVelero"],
    assetNote: "Asset-bank · grupos-experiencia/IMG_4635.MOV",
    editNote: "Abrir con energía de grupo real y gesto compartido; este reemplazo sostiene mucho mejor el ángulo de juntada."
  },
  {
    id: "TT12",
    group: 3,
    title: "Regalá algo que sí se acuerden",
    pillar: "Regalo experiencial",
    objective: "Consulta",
    format: "Video vela al sol / emoción",
    mediaType: "video",
    media: "media/IMG_4575.MOV",
    trimStart: 2.3,
    poster: "posters/IMG_4575.jpg",
    alt: "Velero con luz fuerte sobre el agua",
    hook: "Regalá algo que sí se acuerden",
    screenText: ["No otro objeto", "regalá una experiencia", "que quede en la memoria"],
    captionLead: "Con este material el ángulo regalo entra mejor desde emoción que desde argumento.",
    cta: "Escribinos si querés regalar una salida distinta.",
    hashtags: ["#ENBA", "#RegaloOriginal", "#SalidaEnVelero"],
    assetNote: "Asset-bank · grupos-experiencia/IMG_4575.MOV",
    editNote: "Corte lento y contemplativo; este reemplazo da mejor respiración para la idea de regalo."
  },
  {
    id: "TT13",
    group: 3,
    title: "Armá tu salida privada en velero",
    pillar: "Grupo privado",
    objective: "Plan concreto",
    format: "Video previa / amigos / marina",
    mediaType: "video",
    media: "media/IMG_5631.MOV",
    poster: "posters/IMG_5631.jpg",
    alt: "Previa de salida en marina con plan entre amigos",
    hook: "Armá tu salida privada en velero",
    screenText: ["Amigos", "pareja", "familia", "grupo propio en el río"],
    captionLead: "Acá el foco no es el embarque genérico sino la previa del plan: barco listo, marina y sensación de salida entre amigos.",
    cta: "Pedinos opciones para armar su salida.",
    hashtags: ["#ENBA", "#PlanConAmigos", "#Velero"],
    assetNote: "Nuevo material 27/04 · IMG_5631.MOV",
    editNote: "Usarla como 'así arranca': plano corto, texto claro y cierre con marca ENBA real solo si ayuda a rematar."
  },
  {
    id: "TT14",
    group: 3,
    title: "El río no es solo un plan",
    pillar: "Marca",
    objective: "Marca / deseo",
    format: "Video velero abierto / manifesto",
    mediaType: "video",
    media: "media/b6c0e560-9ba5-42eb-8ab2-30fdcebdbb2e.mp4",
    poster: "posters/b6c0e560.jpg",
    alt: "Velero abierto sobre el río en clave de marca",
    hook: "El río no es solo un plan",
    screenText: ["No es solo un plan", "es otra velocidad", "otra cabeza"],
    captionLead: "Pieza pura de atmósfera, pensada para marca y no para CTA duro.",
    cta: "Seguinos si te tira más este ritmo que el de siempre.",
    hashtags: ["#ENBA", "#espacionautico", "#BuenosAires", "#RioDeLaPlata"],
    assetNote: "Nuevo material 27/04 · b6c0e560 open sail",
    editNote: "Menos texto, más aire; tratarla como manifiesto corto y no como venta. Si entra logo, mejor lockup horizontal real de ENBA en el último segundo."
  },
  {
    id: "TT15",
    group: 3,
    title: "Qué cambia cuando salís de la ciudad pero seguís en Buenos Aires",
    pillar: "Buenos Aires desde el agua",
    objective: "Curiosidad",
    format: "Video vela / ciudad mental",
    mediaType: "video",
    media: "media/IMG_8231.MOV",
    poster: "posters/IMG_8231.jpg",
    alt: "Vela recortada contra cielo y río abierto",
    hook: "Qué cambia cuando salís de la ciudad pero seguís en Buenos Aires",
    screenText: ["Seguís en Buenos Aires", "pero ya no se siente igual", "cuando cambia el ritmo"],
    captionLead: "Concepto muy ENBA: cortar sin irse lejos.",
    cta: "Guardalo para cuando necesites bajar un cambio.",
    hashtags: ["#ENBA", "#BajarUnCambio", "#RioDeLaPlata"],
    assetNote: "Asset-bank · buenos-aires-paisaje/IMG_8231.MOV",
    editNote: "Funciona mejor con ritmo calmo y copy preciso; este reemplazo refuerza el ángulo Buenos Aires / agua."
  },
  {
    id: "TT16",
    group: 4,
    title: "Ver el barco cambia todo",
    pillar: "Navegación real",
    objective: "Autoridad visual",
    format: "Video barco completo / quietud",
    mediaType: "video",
    media: "media/IMG_0596.MOV",
    trimStart: 23.0,
    poster: "posters/IMG_0596.jpg",
    alt: "Barco completo en cuadro abierto",
    hook: "Ver el barco cambia todo",
    screenText: ["Una foto ayuda", "pero ver el barco", "cambia todo"],
    captionLead: "Esta reemplaza el ángulo broker genérico por autoridad visual de navegación real.",
    cta: "Seguinos si querés ver más barco real, no solo fotos.",
    hashtags: ["#ENBA", "#Barco", "#Nautica"],
    assetNote: "Asset-bank · escuela-aprendizaje/IMG_0596.MOV",
    editNote: "Tono más sobrio y corto, menos emocional; este reemplazo da presencia física real del barco."
  },
  {
    id: "TT17",
    group: 4,
    title: "Hay una diferencia entre mirar el río y navegarlo",
    pillar: "Navegación real",
    objective: "Diferenciación",
    format: "Video vela cercana / navegación viva",
    mediaType: "video",
    media: "media/3a93da67-fd00-48d0-a415-65ee16bd2d2a.mp4",
    poster: "posters/3a93da67.jpg",
    alt: "Vela cerca del agua con sensación de navegación real",
    hook: "Hay una diferencia entre mirar el río y navegarlo",
    screenText: ["Mirarlo desde lejos", "no es lo mismo", "que vivirlo a bordo"],
    captionLead: "Sirve para reforzar la propuesta experiencial sin caer en frase vacía.",
    cta: "Escribinos si querés sentirlo, vivilo a bordo.",
    hashtags: ["#ENBA", "#Velero", "#SalidaEnVelero"],
    assetNote: "Nuevo material 27/04 · 3a93da67 sail close-up",
    editNote: "Mantener el texto mínimo y dejar que la cercanía al agua haga el trabajo."
  },
  {
    id: "TT18",
    group: 4,
    title: "Cómo es una navegación real y no un paseo armado",
    pillar: "Travesía",
    objective: "Diferenciación",
    format: "Video tripulación / navegación real",
    mediaType: "video",
    media: "media/IMG_5613.MOV",
    poster: "posters/IMG_5613.jpg",
    alt: "Tripulación y cubierta en navegación abierta",
    hook: "Cómo es una navegación real y no un paseo armado",
    screenText: ["Más río", "más navegación", "menos pose"],
    captionLead: "La pieza trabaja bien si ENBA quiere correr un poco el eje de “paseo” hacia navegación de verdad.",
    cta: "Seguinos si te interesa navegar de verdad.",
    hashtags: ["#ENBA", "#espacionautico", "#Navegacion", "#AprenderANavegar"],
    assetNote: "Nuevo material 27/04 · IMG_5613.MOV",
    editNote: "Texto duro pero visual sereno, para que no suene agresivo ni resentido."
  },
  {
    id: "TT19",
    group: 4,
    title: "Salir al río cambia la escala del plan",
    pillar: "Destinos / horizonte",
    objective: "Aspiración",
    format: "Video velero abierto / horizonte",
    mediaType: "video",
    media: "media/07a54f40-49d1-47f1-92ab-301780f60020.mp4",
    poster: "posters/07a54f40.jpg",
    alt: "Velero abierto con horizonte amplio",
    hook: "Salir al río cambia la escala del plan",
    screenText: ["Ya no es solo un plan", "es otra escala", "otro horizonte"],
    captionLead: "Muy buena para aspiración y para cerrar una tanda con aire.",
    cta: "Guardalo si te gustaría hacer un plan así.",
    hashtags: ["#ENBA", "#PlanDiferente", "#Velero"],
    assetNote: "Nuevo material 27/04 · 07a54f40 horizon sail",
    editNote: "Dejar que el velero lejano respire; no taparlo con demasiado copy."
  },
  {
    id: "TT20",
    group: 4,
    title: "Si nunca navegaste, este es un buen primer paso",
    pillar: "Primera vez",
    objective: "Cierre del sprint",
    format: "Video agua / iniciación",
    mediaType: "video",
    media: "media/IMG_5462.MOV",
    trimStart: 4.0,
    poster: "posters/IMG_5462.jpg",
    previewLoop: false,
    alt: "Agua abierta desde cubierta en primer plano",
    hook: "Si nunca navegaste, este es un buen primer paso",
    screenText: ["No hace falta arrancar enorme", "hace falta arrancar", "y subirte una vez"],
    captionLead: "Buen cierre de piloto: amable, accesible y sin ruido visual.",
    cta: "Escribinos si querés dar ese primer paso.",
    hashtags: ["#ENBA", "#espacionautico", "#PrimeraVez", "#AprenderANavegar"],
    assetNote: "Nuevo material 27/04 · IMG_5462.MOV",
    editNote: "Pensada para cierre suave y CTA simple; este reemplazo aporta presencia humana real."
  }
];
