globalThis.ENBATiktokPieces = [
  {
    id: "TT01",
    group: 1,
    title: "No hace falta irte lejos para vivir esto",
    pillar: "Buenos Aires desde el agua",
    objective: "Discovery",
    format: "Video hero / sunset",
    mediaType: "video",
    media: "file:///C:/Users/josea/OneDrive/Escritorio/ENBA/parachati27042026/956CF4EA-ED6E-49B9-B883-B17C6A2D7403.mp4",
    poster: "posters/956CF4EA.jpg",
    alt: "Atardecer en el río con skyline al fondo",
    hook: "No hace falta irte lejos para vivir esto",
    screenText: ["No hace falta irte lejos", "para vivir esto", "Buenos Aires desde el agua"],
    captionLead: "Abrimos el canal con río, atardecer y ciudad al fondo: el ángulo más fuerte para discovery.",
    cta: "Guardalo para tu próximo finde.",
    assetNote: "Nuevo material 27/04 · clip 956CF4EA sunset skyline",
    editNote: "Mantener el plano respirado y cargar el texto en 3 golpes grandes."
  },
  {
    id: "TT02",
    group: 1,
    title: "Tu primera vez en un velero puede empezar acá",
    pillar: "Primera vez",
    objective: "Fricción baja",
    format: "Video onboard / persona",
    mediaType: "video",
    media: "file:///C:/Users/josea/OneDrive/Escritorio/ENBA/parachati27042026/IMG_5623.MOV",
    poster: "posters/IMG_5623.jpg",
    alt: "Persona en cubierta durante navegación",
    hook: "Tu primera vez en un velero puede empezar acá",
    screenText: ["Tu primera vez", "en un velero", "puede empezar acá"],
    captionLead: "La pieza más clara para bajar ansiedad: se ve gente real, río real y nada de pose turística.",
    cta: "Escribinos si querés vivirlo.",
    assetNote: "Nuevo material 27/04 · IMG_5623.MOV",
    editNote: "Abrir directo con persona a bordo y evitar intro larga."
  },
  {
    id: "TT03",
    group: 1,
    title: "Buenos Aires se ve distinta desde el río",
    pillar: "Buenos Aires desde el agua",
    objective: "Descubrimiento",
    format: "Video skyline / sunset",
    mediaType: "video",
    media: "file:///C:/Users/josea/OneDrive/Escritorio/ENBA/parachati27042026/956CF4EA-ED6E-49B9-B883-B17C6A2D7403.mp4",
    poster: "posters/956CF4EA.jpg",
    alt: "Skyline y río al atardecer",
    hook: "Buenos Aires se ve distinta desde el río",
    screenText: ["Buenos Aires", "se ve distinta", "desde el río"],
    captionLead: "Mismo clip base que TT01, pero con otra promesa y otro recorte emocional.",
    cta: "Seguinos para ver más salidas reales.",
    assetNote: "Nuevo material 27/04 · reutiliza 956CF4EA sunset skyline",
    editNote: "Recortar más corto y dejar entrar el skyline antes del tercer segundo."
  },
  {
    id: "TT04",
    group: 1,
    title: "Qué pasa en una salida real en velero",
    pillar: "Backstage real",
    objective: "Mostrar experiencia",
    format: "Video embarque / marina",
    mediaType: "video",
    media: "file:///C:/Users/josea/OneDrive/Escritorio/ENBA/parachati27042026/IMG_5454.MOV",
    poster: "posters/IMG_5454.jpg",
    alt: "Salida real desde marina",
    hook: "Qué pasa en una salida real en velero",
    screenText: ["Marina", "embarque", "salida real", "río de verdad"],
    captionLead: "Sirve para mostrar secuencia concreta y humana sin depender de reels viejos.",
    cta: "Compartilo con quien se subiría con vos.",
    assetNote: "Nuevo material 27/04 · IMG_5454.MOV",
    editNote: "Editar como recap corto: embarque, paso a bordo y salida."
  },
  {
    id: "TT05",
    group: 1,
    title: "No necesitás experiencia para subirte",
    pillar: "Primera vez",
    objective: "Bajar ansiedad",
    format: "Video POV / agua",
    mediaType: "video",
    media: "file:///C:/Users/josea/OneDrive/Escritorio/ENBA/parachati27042026/IMG_5601.MOV",
    poster: "posters/IMG_5601.jpg",
    alt: "POV del río desde cubierta",
    hook: "No necesitás experiencia para subirte",
    screenText: ["No necesitás experiencia", "ni venir sabiendo", "solo querer probar"],
    captionLead: "El río puede parecer lejano; esta pieza lo vuelve simple y accesible.",
    cta: "Mandáselo a quien siempre dice que le da cosa.",
    assetNote: "Nuevo material 27/04 · IMG_5601.MOV",
    editNote: "Hook textual muy temprano y ritmo amable, casi de invitación."
  },
  {
    id: "TT06",
    group: 2,
    title: "Aprender a navegar no arranca en un aula, arranca acá",
    pillar: "Aprender a navegar",
    objective: "Escuela",
    format: "Video maniobra / cabos",
    mediaType: "video",
    media: "file:///C:/Users/josea/OneDrive/Escritorio/ENBA/parachati27042026/IMG_5492.MOV",
    poster: "posters/IMG_5492.jpg",
    alt: "Maniobra práctica en cubierta",
    hook: "Aprender a navegar no arranca en un aula, arranca acá",
    screenText: ["No arranca en un aula", "arranca en cubierta", "y con práctica real"],
    captionLead: "La pieza más clara para escuela con material nuevo: manos, cabos, acción real.",
    cta: "Consultanos por escuela.",
    assetNote: "Nuevo material 27/04 · IMG_5492.MOV",
    editNote: "Usar primeros planos de acción y una voz en off corta."
  },
  {
    id: "TT07",
    group: 2,
    title: "Lo que nadie te cuenta de aprender a navegar",
    pillar: "Aprender a navegar",
    objective: "Curiosidad",
    format: "Video cubierta / condiciones",
    mediaType: "video",
    media: "file:///C:/Users/josea/OneDrive/Escritorio/ENBA/parachati27042026/IMG_5614.MOV",
    poster: "posters/IMG_5614.jpg",
    alt: "Cubierta y cielo abierto durante navegación",
    hook: "Lo que nadie te cuenta de aprender a navegar",
    screenText: ["No es memorizar", "es leer el barco", "y sentir el río"],
    captionLead: "TikTok agradece este tono medio confidencial cuando el visual sostiene autenticidad.",
    cta: "Seguinos si querés ver más escuela real.",
    assetNote: "Nuevo material 27/04 · IMG_5614.MOV",
    editNote: "Dejar que el cielo y la cubierta hagan atmósfera; no sobrecargar de texto."
  },
  {
    id: "TT08",
    group: 2,
    title: "Así se siente tener el timón por primera vez",
    pillar: "Aprender a navegar",
    objective: "Sensación",
    format: "Video onboard / persona",
    mediaType: "video",
    media: "file:///C:/Users/josea/OneDrive/Escritorio/ENBA/parachati27042026/IMG_5623.MOV",
    poster: "posters/IMG_5623.jpg",
    alt: "Persona navegando en primera experiencia",
    hook: "Así se siente tener el timón por primera vez",
    screenText: ["Primer timón", "primera respuesta", "primer click"],
    captionLead: "Reuso deliberado de un clip fuerte, pero con otro guion y otra emoción.",
    cta: "Guardalo si querés vivir esa sensación.",
    assetNote: "Nuevo material 27/04 · reutiliza IMG_5623.MOV",
    editNote: "Recortar para que entre como sensación, no como paseo."
  },
  {
    id: "TT09",
    group: 2,
    title: "No hace falta venir sabiendo. Hace falta venir",
    pillar: "Escuela",
    objective: "Conversión suave",
    format: "Video vela / cubierta",
    mediaType: "video",
    media: "file:///C:/Users/josea/OneDrive/Escritorio/ENBA/parachati27042026/IMG_5615.MOV",
    poster: "posters/IMG_5615.jpg",
    alt: "Cubierta y vela en movimiento",
    hook: "No hace falta venir sabiendo. Hace falta venir",
    screenText: ["No hace falta venir sabiendo", "hace falta venir", "y practicar"],
    captionLead: "Acá el peso está en la frase y en la sensación de navegación real.",
    cta: "Escribinos si querés empezar.",
    assetNote: "Nuevo material 27/04 · IMG_5615.MOV",
    editNote: "Texto protagonista, imagen como soporte atmosférico."
  },
  {
    id: "TT10",
    group: 2,
    title: "3 cosas que ves en el río cuando subís a un velero",
    pillar: "Aprender a navegar",
    objective: "Formato lista",
    format: "Video openwater / lista",
    mediaType: "video",
    media: "file:///C:/Users/josea/OneDrive/Escritorio/ENBA/parachati27042026/IMG_5600.MOV",
    poster: "posters/IMG_5600.jpg",
    alt: "Río abierto y velero a distancia",
    hook: "3 cosas que ves en el río cuando subís a un velero",
    screenText: ["1. Horizonte real", "2. Tráfico y viento", "3. La ciudad desde otro lugar"],
    captionLead: "Formato lista simple y visual, ideal para testear shares y retención corta.",
    cta: "Comentá cuál te gustaría vivir primero.",
    assetNote: "Nuevo material 27/04 · IMG_5600.MOV",
    editNote: "Mantener 3 beats muy claros y no pasarse de 12-15 segundos."
  },
  {
    id: "TT11",
    group: 3,
    title: "Si tu plan de finde siempre es igual, mirá esto",
    pillar: "Deseo / estilo de vida",
    objective: "Interrupción",
    format: "Video boarding / group vibe",
    mediaType: "video",
    media: "file:///C:/Users/josea/OneDrive/Escritorio/ENBA/parachati27042026/IMG_5327.MP4",
    poster: "posters/IMG_5327.jpg",
    alt: "Grupo embarcando en marina",
    hook: "Si tu plan de finde siempre es igual, mirá esto",
    screenText: ["Si tu finde siempre se ve igual", "capaz el problema", "es el plan"],
    captionLead: "Esta pieza ya arranca más TikTok nativa: movimiento grupal, contexto y promesa simple.",
    cta: "Mandáselo a tu grupo.",
    assetNote: "Nuevo material 27/04 · IMG_5327.MP4",
    editNote: "Meter el texto muy rápido porque el clip es corto."
  },
  {
    id: "TT12",
    group: 3,
    title: "Regalá algo que sí se acuerden",
    pillar: "Regalo experiencial",
    objective: "Consulta",
    format: "Video sunset / emoción",
    mediaType: "video",
    media: "file:///C:/Users/josea/OneDrive/Escritorio/ENBA/parachati27042026/956CF4EA-ED6E-49B9-B883-B17C6A2D7403.mp4",
    poster: "posters/956CF4EA.jpg",
    alt: "Atardecer navegando en el río",
    hook: "Regalá algo que sí se acuerden",
    screenText: ["No otro objeto", "regalá una experiencia", "que quede en la memoria"],
    captionLead: "Con este material el ángulo regalo entra mejor desde emoción que desde argumento.",
    cta: "Escribinos si querés regalar una salida.",
    assetNote: "Nuevo material 27/04 · reutiliza 956CF4EA sunset skyline",
    editNote: "Corte lento y más contemplativo que las piezas de performance."
  },
  {
    id: "TT13",
    group: 3,
    title: "Armá tu salida privada en velero",
    pillar: "Grupo privado",
    objective: "Plan concreto",
    format: "Video marina / grupo",
    mediaType: "video",
    media: "file:///C:/Users/josea/OneDrive/Escritorio/ENBA/parachati27042026/IMG_5330.MP4",
    poster: "posters/IMG_5330.jpg",
    alt: "Segundo ángulo de boarding y grupo en marina",
    hook: "Armá tu salida privada en velero",
    screenText: ["Amigos", "pareja", "familia", "grupo propio en el río"],
    captionLead: "Clip corto, ideal para resolver una pieza ultra concreta y muy de plan compartido.",
    cta: "Pedinos opciones para tu salida.",
    assetNote: "Nuevo material 27/04 · IMG_5330.MP4",
    editNote: "Mantener la edición compacta y sumar texto fuerte porque el clip es breve."
  },
  {
    id: "TT14",
    group: 3,
    title: "El río no es solo un plan",
    pillar: "Marca",
    objective: "Brand desire",
    format: "Video silhouette / manifesto",
    mediaType: "video",
    media: "file:///C:/Users/josea/OneDrive/Escritorio/ENBA/parachati27042026/IMG_5595.MP4",
    poster: "posters/IMG_5595.jpg",
    alt: "Velero en silueta al atardecer",
    hook: "El río no es solo un plan",
    screenText: ["No es solo un plan", "es otra velocidad", "otra cabeza"],
    captionLead: "Pieza pura de atmósfera, pensada para marca y no para CTA duro.",
    cta: "Seguinos para ver más del lado náutico de Buenos Aires.",
    assetNote: "Nuevo material 27/04 · IMG_5595.MP4",
    editNote: "Menos texto, más aire; tratarla como manifiesto corto."
  },
  {
    id: "TT15",
    group: 3,
    title: "Qué cambia cuando salís de la ciudad pero seguís en Buenos Aires",
    pillar: "Buenos Aires desde el agua",
    objective: "Curiosidad",
    format: "Video openwater / mood",
    mediaType: "video",
    media: "file:///C:/Users/josea/OneDrive/Escritorio/ENBA/parachati27042026/IMG_5330.MP4",
    poster: "posters/IMG_5330.jpg",
    alt: "Clip corto de transición marina-río",
    hook: "Qué cambia cuando salís de la ciudad pero seguís en Buenos Aires",
    screenText: ["Seguís en Buenos Aires", "pero ya no se siente igual", "cuando cambia el agua"],
    captionLead: "Concepto muy ENBA: cortar sin irse lejos.",
    cta: "Guardalo para cuando necesites cortar.",
    assetNote: "Nuevo material 27/04 · IMG_5330.MP4",
    editNote: "Funciona mejor con ritmo calmo y copy preciso."
  },
  {
    id: "TT16",
    group: 4,
    title: "Ver el barco cambia todo",
    pillar: "Navegación real",
    objective: "Autoridad visual",
    format: "Video barco completo / quietud",
    mediaType: "video",
    media: "file:///C:/Users/josea/OneDrive/Escritorio/ENBA/parachati27042026/IMG_5318.MP4",
    poster: "posters/IMG_5318.jpg",
    alt: "Barco completo en cuadro abierto",
    hook: "Ver el barco cambia todo",
    screenText: ["Una foto ayuda", "pero ver el barco", "cambia todo"],
    captionLead: "Esta reemplaza el ángulo broker genérico por autoridad visual de navegación real.",
    cta: "Seguinos para ver más material en el río.",
    assetNote: "Nuevo material 27/04 · IMG_5318.MP4",
    editNote: "Tono más sobrio y corto, menos emocional."
  },
  {
    id: "TT17",
    group: 4,
    title: "Hay una diferencia entre mirar el río y navegarlo",
    pillar: "Navegación real",
    objective: "Diferenciación",
    format: "Video POV / agua",
    mediaType: "video",
    media: "file:///C:/Users/josea/OneDrive/Escritorio/ENBA/parachati27042026/IMG_5601.MOV",
    poster: "posters/IMG_5601.jpg",
    alt: "POV de navegación abierta",
    hook: "Hay una diferencia entre mirar el río y navegarlo",
    screenText: ["Mirarlo desde lejos", "no es lo mismo", "que vivirlo arriba"],
    captionLead: "Sirve para reforzar la propuesta experiencial sin caer en frase vacía.",
    cta: "Escribinos si querés probar una salida.",
    assetNote: "Nuevo material 27/04 · reutiliza IMG_5601.MOV",
    editNote: "Mantener el texto mínimo y dejar que el POV haga el trabajo."
  },
  {
    id: "TT18",
    group: 4,
    title: "Cómo es una navegación real y no un paseo armado",
    pillar: "Travesía",
    objective: "Diferenciación",
    format: "Video cubierta / condiciones",
    mediaType: "video",
    media: "file:///C:/Users/josea/OneDrive/Escritorio/ENBA/parachati27042026/IMG_5614.MOV",
    poster: "posters/IMG_5614.jpg",
    alt: "Cubierta y cielo durante navegación real",
    hook: "Cómo es una navegación real y no un paseo armado",
    screenText: ["Más río", "más navegación", "menos acting"],
    captionLead: "La pieza trabaja bien si ENBA quiere correr un poco el eje de “tour” hacia navegación de verdad.",
    cta: "Seguinos si te interesa navegar más de cerca.",
    assetNote: "Nuevo material 27/04 · reutiliza IMG_5614.MOV",
    editNote: "Texto duro pero visual sereno, para que no suene agresivo."
  },
  {
    id: "TT19",
    group: 4,
    title: "Salir al río cambia la escala del plan",
    pillar: "Destinos / horizonte",
    objective: "Aspiración",
    format: "Video velero lejano / horizonte",
    mediaType: "video",
    media: "file:///C:/Users/josea/OneDrive/Escritorio/ENBA/parachati27042026/5c04e430-97c1-42ee-980c-5cfac81e6d66.mp4",
    poster: "posters/5c04e430.jpg",
    alt: "Velero pequeño en horizonte abierto",
    hook: "Salir al río cambia la escala del plan",
    screenText: ["Ya no es solo un plan", "es otra escala", "otro horizonte"],
    captionLead: "Muy buena para aspiración y para cerrar una tanda con aire.",
    cta: "Guardalo si te gustaría hacer algo así.",
    assetNote: "Nuevo material 27/04 · 5c04e430...mp4",
    editNote: "Dejar que el velero lejano respire; no taparlo con demasiado copy."
  },
  {
    id: "TT20",
    group: 4,
    title: "Si nunca navegaste, este es un buen primer paso",
    pillar: "Primera vez",
    objective: "Cierre del sprint",
    format: "Video agua / iniciación",
    mediaType: "video",
    media: "file:///C:/Users/josea/OneDrive/Escritorio/ENBA/parachati27042026/IMG_5518.MP4",
    poster: "posters/IMG_5518.jpg",
    alt: "Agua abierta desde cubierta en primer plano",
    hook: "Si nunca navegaste, este es un buen primer paso",
    screenText: ["No hace falta arrancar enorme", "hace falta arrancar", "y subirte una vez"],
    captionLead: "Buen cierre de piloto: amable, accesible y sin ruido visual.",
    cta: "Escribinos si querés probar una salida.",
    assetNote: "Nuevo material 27/04 · IMG_5518.MP4",
    editNote: "Pensada para cierre suave y CTA simple."
  }
];
